# Generated by Django 6.0 on 2026-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='frequency',
            field=models.CharField(choices=[('single', 'One Shot'), ('weekly', 'Weekly'), ('monthly', 'Monyhly')], default='single', max_length=20),
        ),
    ]
