# Generated by Django 6.0 on 2026-04-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventtype_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('free', 'Free'), ('members', 'Members'), ('collaboration', 'Collaboration')], default='members', max_length=20),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
