# Generated by Django 6.0 on 2026-04-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_level_event_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='events',
            field=models.ManyToManyField(blank=True, to='event.event'),
        ),
    ]
