# Generated by Django 6.0 on 2026-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
