# Generated by Django 6.0 on 2026-04-21 13:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
