# Generated by Django 6.0 on 2026-06-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name='eventtype',
            name='partner_roles',
            field=models.ManyToManyField(blank=True, null=True, to='event.partnerrole'),
        ),
    ]
