# Generated by Django 6.0 on 2026-06-05 11:39

from django.db import migrations


def seed_roles(apps, schema_editor):
    # IMPORTANT: always get the model via apps.get_model(), never import directly.
    # This gives you the "historical" version of the model at this point in time,
    # which is safe even if the model changes in future migrations.
    PartnerRole = apps.get_model('event', 'PartnerRole')

    partner_roles = [
        {'name': 'Leader'},
        {'name': 'Follower'},
        {'name': 'Both'},
    ]

    for data in partner_roles:
        PartnerRole.objects.get_or_create(
            name=data['name'],
        )


def reverse_seed_roles(apps, schema_editor):
    # Defines what happens on migrate --reverse (optional but good practice)
    PartnerRole = apps.get_model('event', 'ParterRole')
    PartnerRole.objects.filter(name__in=['Leader', 'Follower', 'Both']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_partnerrole_eventtype_partner_roles'),
    ]

    operations = [
        migrations.RunPython(
            seed_roles,  # forward: applied on migrate
            reverse_seed_roles,  # backward: applied on migrate --reverse
        ),
    ]