# Generated by Django 6.0 on 2026-06-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_PartnerRole'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepted_roles',
            field=models.ManyToManyField(blank=True, null=True, to='event.partnerrole'),
        ),
        migrations.AddField(
            model_name='event',
            name='extras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_days',
            field=models.IntegerField(default=7, verbose_name='Giorni per pagare'),
        ),
        migrations.AddField(
            model_name='event',
            name='warning_threshold',
            field=models.IntegerField(default=5, verbose_name='Warning Threshold'),
        ),
    ]
