# Generated by Django 6.0 on 2026-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_accepted_roles_event_extras_event_payment_days_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE event_event SET extras = '0' WHERE extras IS NULL OR extras = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='event',
            name='extras',
            field=models.IntegerField(default=0),
        ),
    ]
