# Generated by Django 6.0 on 2026-06-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_event_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_days_waiting',
            field=models.IntegerField(default=1, verbose_name='Giorni per pagare rientrati dalla waiting list'),
        ),
    ]
