# Generated by Django 6.0 on 2026-06-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_event_payment_days_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='multi_events',
            field=models.BooleanField(default=False),
        ),
    ]
