# Generated by Django 6.0 on 2026-06-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_event_free_event_multi_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='party',
            field=models.BooleanField(default=False),
        ),
    ]
