# Generated by Django 6.0 on 2026-06-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_eventtype_party'),
        ('membership', '0009_remove_membership_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='memberships',
            field=models.ManyToManyField(blank=True, related_name='events', to='membership.membership'),
        ),
    ]
