# Generated by Django 6.0 on 2026-07-30 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_event_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('it', 'Italiano')], max_length=10)),
                ('desc', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='event.event')),
            ],
            options={
                'unique_together': {('event', 'language')},
            },
        ),
    ]
