# Generated by Django 6.0 on 2026-09-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_eventdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='block_payment',
            field=models.BooleanField(default=False),
        ),
    ]
