# Generated by Django 6.0 on 2026-04-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0004_level_event_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('single', 'Single'), ('monthly', 'Monthly'), ('quarter', 'Quarter'), ('year', 'Year')], default='single', max_length=20)),
                ('contribution', models.IntegerField(default=0)),
                ('max_courses', models.IntegerField(default=0)),
                ('max_parties', models.IntegerField(default=0)),
                ('events', models.ManyToManyField(to='event.event')),
            ],
        ),
    ]
