# Generated by Django 6.0 on 2026-04-20 15:53

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_level_event_level'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='membership',
            name='events',
            field=models.ManyToManyField(blank=True, to='event.event'),
        ),
    ]
