# Generated by Django 6.0 on 2026-04-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_color'),
        ('membership', '0002_membership_color_alter_membership_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='events',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='max_courses',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='max_parties',
        ),
        migrations.CreateModel(
            name='MembershipRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_events', models.IntegerField(default=1)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.eventtype')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.membership')),
            ],
        ),
    ]
