# Generated by Django 6.0 on 2026-04-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_remove_membership_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='max_events',
            field=models.IntegerField(default=0),
        ),
    ]
