# Generated by Django 6.0 on 2026-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_membership_max_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration (months)'),
        ),
    ]
