# Generated by Django 6.0 on 2026-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_membership_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('name_ext', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Pack', 'verbose_name_plural': 'Packs'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='max_events',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
