# Generated by Django 6.0 on 2026-06-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_event_free_event_multi_events'),
        ('membership', '0007_seed_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.event'),
        ),
    ]
