# Generated by Django 6.0 on 2026-06-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_membership_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='event',
        ),
    ]
