# Generated by Django 6.0 on 2026-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_eventdescription'),
        ('membership', '0010_membership_end_date_membership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='fix_events',
            field=models.ManyToManyField(blank=True, related_name='included_in_memberships', to='event.event'),
        ),
    ]
