# Generated by Django 6.0 on 2026-09-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_membership_fix_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='only_cash',
            field=models.BooleanField(default=False),
        ),
    ]
