# Generated by Django 6.0 on 2026-09-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_membership_only_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='couple',
            field=models.BooleanField(default=False),
        ),
    ]
