# Generated by Django 6.0 on 2026-04-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0006_event_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='FesivalRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.room')),
                ('festival_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='festival.festivalday')),
            ],
        ),
    ]
