# Generated by Django 6.0 on 2026-06-23 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_event_free_event_multi_events'),
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fesivalroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.room'),
        ),
        migrations.AlterField(
            model_name='festivalday',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
