# Generated by Django 6.0 on 2026-06-23 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_alter_fesivalroom_room_alter_festivalday_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fesivalroom',
            name='festival_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.festivalday'),
        ),
    ]
