# Generated by Django 6.0 on 2026-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
