# Generated by Django 6.0 on 2026-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_contribution_end_date_contribution_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('accepted', 'Accepted'), ('paid', 'Paid')], default='received', max_length=20),
        ),
    ]
