# Generated by Django 6.0 on 2026-04-24 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_contribution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='upgraded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.contribution'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed')], default='received', max_length=20),
        ),
    ]
