# Generated by Django 6.0 on 2026-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_contribution_upgraded_from_alter_contribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('payed', 'Payed')], default='received', max_length=20),
        ),
    ]
