# Generated by Django 6.0 on 2026-06-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_contribution_status'),
        ('event', '0009_partnerrole_eventtype_partner_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.partnerrole'),
        ),
    ]
