# Generated by Django 6.0 on 2026-06-09 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_contribution_partner_contribution_partner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='original_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twin_contributions', to='booking.contribution'),
        ),
    ]
