# Generated by Django 6.0 on 2026-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_load_booking_registration_accepted_email_templates'),
        ('membership', '0007_seed_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='contributions', to='membership.discount'),
        ),
    ]
