# Generated by Django 6.0 on 2026-06-16 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_contribution_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
