# Generated by Django 6.0 on 2026-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_load_contribution_expiry_reminder_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('payed', 'Payed'), ('cancelled', 'Cancelled')], default='received', max_length=20),
        ),
    ]
