# Generated by Django 6.0 on 2026-06-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_load_payment_success_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
