# Generated by Django 6.0 on 2026-06-23 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_load_cancellation_email_template'),
        ('event', '0015_eventtype_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.level'),
        ),
    ]
