# Generated by Django 6.0 on 2026-07-09 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_contribution_level'),
        ('event', '0016_event_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.partnerrole'),
        ),
    ]
