# Generated by Django 6.0 on 2026-07-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_booking_attended_booking_partner_email_booking_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='couple',
            field=models.BooleanField(default=False),
        ),
    ]
