# Generated by Django 6.0 on 2026-07-13 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_booking_contribution_booking_partner_and_more'),
        ('event', '0016_event_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='partner_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_role', to='event.partnerrole'),
        ),
    ]
