# Generated by Django 6.0 on 2026-07-15 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_booking_partner_role'),
        ('event', '0016_event_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_booking_user_event'),
        ),
    ]
