# Generated by Django 6.0 on 2026-08-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_load_acsi_extra_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='extra_items',
            field=models.ManyToManyField(blank=True, related_name='contributions', to='booking.extraitem'),
        ),
    ]
