# Generated by Django 6.0 on 2026-09-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_contribution_extra_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('payed', 'Payed'), ('cancelled', 'Cancelled'), ('waiting', 'Waiting'), ('approving', 'Approving')], default='received', max_length=20),
        ),
    ]
