# Generated by Django 6.0 on 2026-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_load_transaction_completed_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
