# Generated by Django 6.0 on 2026-10-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_contribution_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
