apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-files
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Gi