# Generated by Django 6.0 on 2026-06-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_load_registration_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('it', 'Italiano'), ('en', 'English')], default='it', max_length=2),
        ),
    ]
