# Generated by Django 6.0 on 2026-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_password_reset_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acsi_starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
