# Generated by Django 6.0 on 2026-08-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_acsi_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acsi_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
